version: "1.0"

volumes:
  db_data:

services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_PASSWORD: 123456789
    volumes:
      - db_data:/var/lib/mysql
