version: "1.0"

volumes:
  db_data:

services:
  compiler:
      build:
          context: .
      image: todo-server:latest
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      environment:
        DATABASE_URL: postgres://postgres:123456789@database:5432/todo?schema=public
      working_dir: /app
  database:
    image: postgres:14.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: todo
    volumes:
      - db_data:/var/lib/todo/postgresql/data
      - type: tmpfs
        target: /dev/shm
